export const CHECK_BOOKING_AVAILABILITY_REQUEST =
  "CHECK_BOOKING_AVAILABILITY_REQUEST"
export const CHECK_BOOKING_AVAILABILITY_SUCCESS =
  "CHECK_BOOKING_AVAILABILITY_SUCCESS"
export const CHECK_BOOKING_AVAILABILITY_FAIL = "CHECK_BOOKING_AVAILABILITY_FAIL"
