export const CHECK_BOOKING_AVAILABILITY_REQUEST =
  "CHECK_BOOKING_AVAILABILITY_REQUEST"
export const CHECK_BOOKING_AVAILABILITY_SUCCESS =
  "CHECK_BOOKING_AVAILABILITY_SUCCESS"
export const CHECK_BOOKING_AVAILABILITY_FAIL = "CHECK_BOOKING_AVAILABILITY_FAIL"

export const GET_BOOKED_DATES_SUCCESS = "GET_BOOKED_DATES_SUCCESS"
export const GET_BOOKED_DATES_FAIL = "GET_BOOKED_DATES_FAIL"

export const GET_MY_BOOKINGS_SUCCESS = "GET_MY_BOOKINGS_SUCCESS"
export const GET_MY_BOOKINGS_FAIL = "GET_MY_BOOKINGS_FAIL"
