export const ALL_ROOMS_SUCCESS = "ALL_ROOMS_SUCCESS"
export const ALL_ROOMS_FAIL = "ALL_ROOMS_FAIL"

export const ROOM_DETAILS_SUCCESS = "ROOM_DETAILS_SUCCESS"
export const ROOM_DETAILS_FAIL = "ROOM_DETAILS_FAIL"

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST"
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS"
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL"

export const CHECK_REVIEW_AVAILABILITY_REQUEST =
  "CHECK_REVIEW_AVAILABILITY_REQUEST"
export const CHECK_REVIEW_AVAILABILITY_SUCCESS =
  "CHECK_REVIEW_AVAILABILITY_SUCCESS"
export const CHECK_REVIEW_AVAILABILITY_FAIL = "CHECK_REVIEW_AVAILABILITY_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"
